### ISSUE TITLE
Commit a8ba8a08 fails to compile code

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#122]
With the current master (commit as above) I get the following error messages when I try to compile RapydScript code. The immediately prior commit, 1efde688 works OK.

C:\Users\Phil\RapydScript\lib\compile.js:405
        toplevel: toplevel,
                  ^

ReferenceError: toplevel is not defined
    at module.exports (C:\Users\Phil\RapydScript\lib\compile.js:405:19)
    at Object.<anonymous> (C:\Users\Phil\RapydScript\bin\rapydscript:52:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by jpcharlesworth** [comment]
I should have added that I am compiling on Windows 7 and the current version of Node is 4.6.0 but the same errors was experienced with Node 6.6.0
